### ISSUE TITLE
Posix impl uses TryForm without importing it

### ISSUE THREAD

**Issue by Visic** [DoumanAsh/os-sync#3]
I've made a pull request for this, but all we need to do is add a "use core::convert::TryFrom" and push a new version to make it work again.

**Comment by DoumanAsh** [comment]
Could you please elaborate what is broken?

**Comment by DoumanAsh** [comment]
Hmm so I actually used try_from and it didn't fail in github actions, welp this is weird.
Was it in prelude before?

**Comment by DoumanAsh** [comment]
0.3.3 is released
